Fix error  msm_show_resume_irq.c
Mismatch between format specifier and argument type:

You are using %d (which expects an int) to print a long type, specifically the result of PTR_ERR(base). This causes a format mismatch warning/error.

use %ld
drivers/irqchip/msm_show_resume_irq.c:171:24: error: format specifies type 'int' but the argument has type 'long' [-Werror,-Wformat]
  170 |                 pr_err("%pOF: error %d: unable to map GICD registers\n",
      |                                     ~~
      |                                     %ld
  171 |                                 pdev->dev.of_node, PTR_ERR(base));
      |                                                    ^~~~~~~~~~~~~